"""empty message

Revision ID: 1eca56e2d2b3
Revises: 2e0ec5948584
Create Date: 2015-06-02 15:38:01.421000

"""

# revision identifiers, used by Alembic.
revision = '1eca56e2d2b3'
down_revision = '2e0ec5948584'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('softwares', sa.Column('website', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('softwares', 'website')
    ### end Alembic commands ###
