"""empty message

Revision ID: 2fc38f678ade
Revises: None
Create Date: 2015-05-15 21:47:44.262000

"""

# revision identifiers, used by Alembic.
revision = '2fc38f678ade'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
