"""empty message

Revision ID: 337e6ccffe0
Revises: 1698486472d9
Create Date: 2015-07-21 13:38:38.852000

"""

# revision identifiers, used by Alembic.
revision = '337e6ccffe0'
down_revision = '1698486472d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procons',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('kind', sa.String(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('software_name', sa.String(), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['software_name'], ['softwares.name'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('procons_upvotes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('upvote_date', sa.DateTime(), nullable=True),
                    sa.Column('procons_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['procons_id'], ['procons.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procons_upvotes')
    op.drop_table('procons')
    ### end Alembic commands ###
