"""empty message

Revision ID: 3c7ac204a8d8
Revises: 337e6ccffe0
Create Date: 2015-08-19 22:25:03.681000

"""

# revision identifiers, used by Alembic.
revision = '3c7ac204a8d8'
down_revision = '337e6ccffe0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twitter_access_token', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('twitter_secret_token', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitter_secret_token')
    op.drop_column('users', 'twitter_access_token')
    ### end Alembic commands ###
