"""empty message

Revision ID: 48efda71d7cb
Revises: 29edd350b3da
Create Date: 2014-11-17 17:46:22.932000

"""

# revision identifiers, used by Alembic.
revision = '48efda71d7cb'
down_revision = '29edd350b3da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('softwares', sa.Column('rating', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('softwares', 'rating')
    ### end Alembic commands ###
